In [3]:
!pip install pandas

   ---------------------------------------- 0.0/11.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.5 MB 660.6 kB/s eta 0:00:18
   ---------------------------------------- 0.1/11.5 MB 1.5 MB/s eta 0:00:08
    --------------------------------------- 0.2/11.5 MB 1.4 MB/s eta 0:00:09
    --------------------------------------- 0.3/11.5 MB 1.5 MB/s eta 0:00:08
   - -------------------------------------- 0.3/11.5 MB 1.5 MB/s eta 0:00:08
   - -------------------------------------- 0.4/11.5 MB 1.6 MB/s eta 0:00:08
   - -------------------------------------- 0.5/11.5 MB 1.6 MB/s eta 0:00:08
   - -------------------------------------- 0.6/11.5 MB 1.6 MB/s eta 0:00:07
   -- ------------------------------------- 0.6/11.5 MB 1.6 MB/s eta 0:00:07
   -- ------------------------------------- 0.7/11.5 MB 1.6 MB/s eta 0:00:07
   -- ------------------------------------- 0.8/11.5 MB 1.6 MB/s eta 0:00:07
   --- ------------------------------------ 0.9/11.5 MB 1.6 MB/s eta 0:00:07
   -

## Data Loading

In [4]:
import torch
import numpy as pd
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [5]:
df = pd.read_csv('Data/iris.csv')

In [6]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0     0.0  
1     0.0  
2     0.0  
3     0.0  
4     0.0

In [7]:
!pip install scikit-learn

     ---------------------------------------- 0.0/60.6 kB ? eta -:--:--
     ------ --------------------------------- 10.2/60.6 kB ? eta -:--:--
     ------ --------------------------------- 10.2/60.6 kB ? eta -:--:--
     -------------------------------- ----- 51.2/60.6 kB 375.8 kB/s eta 0:00:01
     -------------------------------------- 60.6/60.6 kB 461.8 kB/s eta 0:00:00
   ---------------------------------------- 0.0/10.9 MB ? eta -:--:--
   ---------------------------------------- 0.1/10.9 MB 1.9 MB/s eta 0:00:06
    --------------------------------------- 0.2/10.9 MB 1.8 MB/s eta 0:00:06
    --------------------------------------- 0.2/10.9 MB 1.8 MB/s eta 0:00:06
   - -------------------------------------- 0.3/10.9 MB 1.9 MB/s eta 0:00:06
   - -------------------------------------- 0.4/10.9 MB 1.7 MB/s eta 0:00:07
   - -------------------------------------- 0.5/10.9 MB 1.8 MB/s eta 0:00:06
   -- ------------------------------------- 0.6/10.9 MB 1.7 MB/s eta 0:00:06
   -- -------

In [8]:
from sklearn.model_selection import train_test_split 

In [9]:
features = df.drop('target', axis = 1).values
label = df['target'].values

In [10]:
X_train, X_test, y_train, y_test = train_test_split(features, label, test_size=0.2, random_state=33)

In [17]:
X_train = torch.FloatTensor(X_train)
X_test = torch.FloatTensor(X_test)

In [19]:
y_train = torch.LongTensor(y_train).reshape(-1, 1)
y_test = torch.LongTensor(y_test).reshape(-1, 1)

In [20]:
from torch.utils.data import TensorDataset, DataLoader


In [21]:
data = df.drop('target', axis=1).values
labels = df['target'].values

In [22]:
iris = TensorDataset(torch.FloatTensor(data), torch.LongTensor(labels))

In [24]:
type(iris)

torch.utils.data.dataset.TensorDataset

In [25]:
len(iris)

150

In [26]:
for i in iris:
    print(i)

(tensor([5.1000, 3.5000, 1.4000, 0.2000]), tensor(0))
(tensor([4.9000, 3.0000, 1.4000, 0.2000]), tensor(0))
(tensor([4.7000, 3.2000, 1.3000, 0.2000]), tensor(0))
(tensor([4.6000, 3.1000, 1.5000, 0.2000]), tensor(0))
(tensor([5.0000, 3.6000, 1.4000, 0.2000]), tensor(0))
(tensor([5.4000, 3.9000, 1.7000, 0.4000]), tensor(0))
(tensor([4.6000, 3.4000, 1.4000, 0.3000]), tensor(0))
(tensor([5.0000, 3.4000, 1.5000, 0.2000]), tensor(0))
(tensor([4.4000, 2.9000, 1.4000, 0.2000]), tensor(0))
(tensor([4.9000, 3.1000, 1.5000, 0.1000]), tensor(0))
(tensor([5.4000, 3.7000, 1.5000, 0.2000]), tensor(0))
(tensor([4.8000, 3.4000, 1.6000, 0.2000]), tensor(0))
(tensor([4.8000, 3.0000, 1.4000, 0.1000]), tensor(0))
(tensor([4.3000, 3.0000, 1.1000, 0.1000]), tensor(0))
(tensor([5.8000, 4.0000, 1.2000, 0.2000]), tensor(0))
(tensor([5.7000, 4.4000, 1.5000, 0.4000]), tensor(0))
(tensor([5.4000, 3.9000, 1.3000, 0.4000]), tensor(0))
(tensor([5.1000, 3.5000, 1.4000, 0.3000]), tensor(0))
(tensor([5.7000, 3.8000, 1.7

In [28]:
iris_loader = DataLoader(iris, batch_size=50, shuffle=True)

In [30]:
for i_batch, sample_batch in enumerate(iris_loader):
    print(i_batch, sample_batch)

0 [tensor([[6.0000, 2.2000, 4.0000, 1.0000],
        [5.1000, 3.4000, 1.5000, 0.2000],
        [6.6000, 3.0000, 4.4000, 1.4000],
        [6.3000, 2.7000, 4.9000, 1.8000],
        [5.8000, 2.7000, 3.9000, 1.2000],
        [7.7000, 3.0000, 6.1000, 2.3000],
        [5.0000, 2.3000, 3.3000, 1.0000],
        [4.9000, 2.4000, 3.3000, 1.0000],
        [5.8000, 2.7000, 5.1000, 1.9000],
        [5.6000, 2.5000, 3.9000, 1.1000],
        [4.6000, 3.4000, 1.4000, 0.3000],
        [5.2000, 3.4000, 1.4000, 0.2000],
        [5.6000, 2.7000, 4.2000, 1.3000],
        [5.5000, 2.4000, 3.8000, 1.1000],
        [6.7000, 3.0000, 5.2000, 2.3000],
        [5.2000, 2.7000, 3.9000, 1.4000],
        [5.0000, 3.3000, 1.4000, 0.2000],
        [6.7000, 3.0000, 5.0000, 1.7000],
        [6.0000, 3.0000, 4.8000, 1.8000],
        [7.7000, 2.8000, 6.7000, 2.0000],
        [6.1000, 2.6000, 5.6000, 1.4000],
        [4.4000, 3.2000, 1.3000, 0.2000],
        [7.9000, 3.8000, 6.4000, 2.0000],
        [5.0000, 3.4000, 1.6000

## ANN Construction

In [31]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [36]:
class Model(nn.Module):
    def __init__(self, in_features=4, h1=8, h2=9, out_features=3):
        # Atributo por cada capa
        super().__init__()
        self.fc1 = nn.Linear(in_features, h1)
        self.fc2 = nn.Linear(h1, h2)
        self.out = nn.Linear(h2, out_features)
        
        # input layer (4 features) -> h1 -> h2 -> output (3 clases)
    
    def forward(self, x):
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = F.relu(self.out(x))
        
        return x

In [91]:
torch.manual_seed(32)

## Data visualization

In [73]:
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [74]:
df = pd.read_csv('Data/iris.csv')

In [75]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0     0.0  
1     0.0  
2     0.0  
3     0.0  
4     0.0

In [76]:
X = df.drop('target', axis=1)
y = df['target']

In [77]:
type(y)

pandas.core.series.Series

In [78]:
X = X.values
y = y.values

In [79]:
from sklearn.model_selection import train_test_split

In [80]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=33)


In [81]:
X_train = torch.FloatTensor(X_train)
X_test = torch.FloatTensor(X_test)
y_train = torch.LongTensor(y_train)
y_test = torch.LongTensor(y_test)

In [93]:
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.0001)

In [83]:
model.parameters()

<generator object Module.parameters at 0x000001E690397060>

In [52]:
model.parameters

<bound method Module.parameters of Model(
  (fc1): Linear(in_features=4, out_features=8, bias=True)
  (fc2): Linear(in_features=8, out_features=9, bias=True)
  (out): Linear(in_features=9, out_features=3, bias=True)
)>

In [56]:
# epoch = 1 prueba de todo el training dataset

epochs = 100
losses = []

In [142]:
for i in range(epochs):
    y_pred = model.forward(X_train)
    loss = criterion(y_pred, y_train)
    losses.append(loss)
    if i%10==0:
        print(f"epoch {i} loss: {loss}")
    
    # Backpropagation
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

epoch 0 loss: 0.09569887071847916
epoch 10 loss: 0.09536583721637726
epoch 20 loss: 0.09503551572561264
epoch 30 loss: 0.09470782428979874
epoch 40 loss: 0.09438268095254898
epoch 50 loss: 0.09405996650457382
epoch 60 loss: 0.09373994916677475
epoch 70 loss: 0.09342250972986221
epoch 80 loss: 0.09310755133628845
epoch 90 loss: 0.09279493987560272


In [145]:
with torch.no_grad():
    y_eval = model.forward(X_test)
    loss = criterion(y_eval, y_test)

In [146]:
loss

tensor(0.1101)

In [152]:
correct = 0
with torch.no_grad():
    for i, data in enumerate(X_test):
        y_val = model.forward(data)
        print(f'{i+1}.) {str(y_val)} --> {y_test[i]}')

        if y_val.argmax().item() == y_test[i]:
            correct+=1

print(f'Correct: {correct} Percentage: {correct/len(X_test)}')

1.) tensor([1.2774, 6.4153, 2.9272]) --> 1
2.) tensor([1.6989, 7.0908, 2.7378]) --> 1
3.) tensor([8.6786, 4.4547, 0.0000]) --> 0
4.) tensor([0.3679, 7.0694, 5.0381]) --> 1
5.) tensor([0.0000, 7.2243, 9.2591]) --> 2
6.) tensor([ 0.0000,  7.8403, 12.9250]) --> 2
7.) tensor([8.6549, 4.6600, 0.0000]) --> 0
8.) tensor([9.2935, 4.6404, 0.0000]) --> 0
9.) tensor([0.0000, 7.4851, 8.9140]) --> 2
10.) tensor([ 0.0000,  7.9810, 11.2503]) --> 2
11.) tensor([ 0.0000,  8.0087, 12.0757]) --> 2
12.) tensor([8.3085, 4.1785, 0.0000]) --> 0
13.) tensor([ 0.0000,  7.6463, 11.1662]) --> 2
14.) tensor([0.3268, 6.8702, 4.9488]) --> 1
15.) tensor([0.0000, 7.7253, 9.3179]) --> 2
16.) tensor([1.5694, 6.8442, 2.7641]) --> 1
17.) tensor([0.0000, 6.9665, 6.9144]) --> 2
18.) tensor([9.4212, 4.7131, 0.0000]) --> 0
19.) tensor([0.6987, 7.0589, 4.4546]) --> 1
20.) tensor([0.0000, 8.1420, 9.8579]) --> 2
21.) tensor([8.8699, 4.5035, 0.0000]) --> 0
22.) tensor([9.9788, 5.0957, 0.0000]) --> 0
23.) tensor([ 0.0000,  7.7621

## Save model

In [158]:
torch.save(model.state_dict(), 'wb_iris_model.pt')
torch.save(model,'iris_model.pt')


In [154]:
new_model = Model()
new_model.load_state_dict(torch.load('iris_model.pt'))

<All keys matched successfully>